---
title: "MSD Open"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rhdf5)
```

```{r}
h5ls("MillionSongSubset/A/Y/Y/TRAYYBD128F9335F7A.h5")
```

```{r}
analysis <- h5read("MillionSongSubset/A/Y/Y/TRAYYBD128F9335F7A.h5",
       name = "/analysis")
```

```{r}
metadata <- h5read("MillionSongSubset/A/Y/Y/TRAYYBD128F9335F7A.h5",
                   name = "/metadata")
```

```{r}
musicbrain <- h5read("MillionSongSubset/A/Y/Y/TRAYYBD128F9335F7A.h5",
                   name = "/musicbrainz")
```


```{r}
dim(analysis$segments_pitches)
```

Given that the dimension of factors in `analysis` will widely vary depending on the song, should we try to find a way to project data into some n dimensions or find a way to start working with info for songs with same dimensionality (e.g. only work with values stored under `song` in the `analysis` section).


```{r}
h5ls("MillionSongSubset/B/F/S/TRBFSEX128F9300418.h5")
```
```{r}
md2 <- h5read("MillionSongSubset/B/F/S/TRBFSEX128F9300418.h5",
       name = "metadata")
```

```{r}
analysis2 <- h5read("MillionSongSubset/B/F/S/TRBFSEX128F9300418.h5",
                    name = "/analysis")
```

```{r}
in_folder <- function(folder) {
  lapply(list.files(folder), function(x) {paste(folder, x, sep = "/")})
}
```

```{r}
mss1 <- lapply(in_folder("MillionSongSubset"), in_folder)
```

```{r}
mss2 <- lapply(mss1[[1]], in_folder)
```

```{r}
mss3 <- lapply(mss2[[1]], in_folder)
```

```{r}
mss_files <- unlist(mss3)
```

```{r}
analysis_list <- lapply(mss_files, function(x){
  h5read(x,
         name = "/analysis")
})
```

```{r}
song_info <- data.frame(analysis_list[[1]]$songs)

for(i in 2:length(analysis_list)) {
  new_row <- analysis_list[[i]]$songs
  song_info <- rbind(song_info, new_row)
}
```

