---
title: "Results"
author: "Harpeth Lee"
date: "4/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Results

## Data Simulation

Our data simulations are done based on the latent variable model that PLS methods assume. We generate $\textbf{X}$ and $\textbf{Y}$ using the following equations, $\textbf{X} = \boldsymbol{\phi} \textbf{A} + \boldsymbol{\epsilon}_X$ and $\textbf{Y} = \boldsymbol{\phi} \textbf{D} + \boldsymbol{\epsilon}_Y$. The $\textbf{A}$ and $\textbf{D}$ matrices are fixed, providing most of the structure seen in $\textbf{X}$ and $\textbf{Y}$. $\boldsymbol{\phi}$, $\boldsymbol{\epsilon}_X$, and $\boldsymbol{\epsilon}_Y$ are randomly generated. The method by which $\boldsymbol{\phi}$ is generated is less important as we want to approximate $\boldsymbol{\phi}$ with our final model. $\boldsymbol{\epsilon}_X$, and $\boldsymbol{\epsilon}_Y$ are sampled from a normal distribution.

Although $\boldsymbol{\phi}$ is generated using a similar method as $\boldsymbol{\epsilon}_X$, and $\boldsymbol{\epsilon}_Y$, it is important to note that $\boldsymbol{\epsilon}_X$ and $\boldsymbol{\epsilon}_Y$ are noise while $\boldsymbol{\phi}$ is not. Ideally, our models will be able to identify $\boldsymbol{\phi}$ while ignoring $\boldsymbol{\epsilon}_X$ and $\boldsymbol{\epsilon}_Y$. $\boldsymbol{\phi}$ is generated sampling from a multivariate normal distribution with uncorrelated samples(using the `mvrnorm` function in the `MASS` package in order to make sure columns are uncorrelated). $\boldsymbol{\epsilon}_X$ and $\boldsymbol{\epsilon}_Y$ are generated by samples from random distributions (using `rnorm`) as this will cause some random correlation in the noise. This random correlation is included as we want to test model's ability to distinguish true correlation from random correlation.


Discuss Helland and Almoy here, maybe this should all be in the theory section.


## Noise




## Predictors



